# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-08 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('BirthDate', models.DateField()),
                ('dateAdd', models.DateField(auto_now_add=True)),
                ('dateEdit', models.DateField(auto_now=True)),
            ],
        ),
    ]
